# FROM python:3.9.1

# RUN apt-get install wget
# RUN pip install pandas sqlalchemy psycopg2

# WORKDIR /app
# COPY ingest_data1.py ingest_data1.py

# ENTRYPOINT [ "python", "ingest_data1.py" ]

FROM python:3.9.0

WORKDIR /app

ENTRYPOINT [ "pip", "list" ]

# FROM python:3.9.1

# WORKDIR /app

# COPY class1.py class1.py

# RUN pip install argparse

# ENTRYPOINT [ "python", "class1.py" ]